### ISSUE TITLE
Support /next/X on the time API.

### ISSUE THREAD

**Issue by chriskessel** [flightstats/hub#1011]
It'd be useful if the time api supported /next/X and /previous/X.

Dev Services Flight Status Feed product is basically a thin layer on top of the Hub interface. Customers currently fetch specific hub items and do /next/X and /previous/X on those items. We'd like to convert to using the second based URIs so we can bulk fetch. This would decouple us from the specifics of how DP is writing the ProcessedFlightHistory entries (how often and how big).

However, there's no /next/X functionality on the time APIs, so if a customer asks what the next 10 URIs are from some previous URI, time API doesn't support that. 

I'd like to be able to query something like this:

http://hub.iad.prod.flightstats.io/channel/ProcessedFlightHistory/2018/01/11/18/30/47/next/10 

and it'd return (in normal JSON /next/X format):

http://hub.iad.prod.flightstats.io/channel/ProcessedFlightHistory/2018/01/11/18/30/48
http://hub.iad.prod.flightstats.io/channel/ProcessedFlightHistory/2018/01/11/18/30/49
http://hub.iad.prod.flightstats.io/channel/ProcessedFlightHistory/2018/01/11/18/30/50
http://hub.iad.prod.flightstats.io/channel/ProcessedFlightHistory/2018/01/11/18/30/51

The big value here is the hub has the smarts to only return completed seconds (closed to writes). So, in this example it only returns 4 entries because those are the only 4 seconds available.

FWIW, we tell customers to do the following when they code to our feed api. If /next/X and previous/X exist on the time apis, we can move customers to the second based fetching without them changing any code.

* Request 'latest'
* Request and process payload of the 'latest' unique url
* Using the same unique url, request the next/'n' list
* Loop through this list of unique urls, requesting and processing the flight status payloads
* When finished use the last unique url to request the next/'n'
* Continue

**Comment by moulliet** [comment]
@chriskessel Currently, if a user calls item/next/N, the system returns a list of hub items.
In your proposed change, calling time/next/N returns a list of times, rather than a list of items.
Wouldn't that require the end users to change their code?

If the intent is for the hub to return time urls, should they only be for times with items, or should we just return the next N completely stable time urls?

**Comment by chriskessel** [comment]
The end users are told to treat the URLS as unique identifiers and to use them exactly as we return them. So, while customers would start getting URLs to the second rather than specific items, but that doesn't matter if they're then turning around and doing a GET on those URLs.

When we'd receive a request to the second, we'd bulk fetch that second behind the scenes and return all the data in that second.

Despite strong warnings not to do so in our docs, there will probably be some customer that violates that and they'll have to fix their broken code.

**Comment by moulliet** [comment]
Returning all the time urls is even easier for us, since we wouldn't need to do a query.
Do you intend to use this for any time unit other than seconds?

**Comment by chriskessel** [comment]
At this point, the only use case is for /next/X on seconds.
