### ISSUE TITLE
Unpaused web hook still shows as paused

### ISSUE THREAD

**Issue by aashishpatel** [flightstats/hub#1034]
This webhook started as "paused" with 3 parallel calls:
http://hub.iad.prod.flightstats.io/webhook/aav2_reloadFlightStatusToAnalytics

I updated it to "unpaused" and 1 parallel calls, but the webhook properties still shows it's paused.  

(I do remember submitting a similar issue for the opposite condition, where I requested the webhook to "pause" and it's marks as such but still processing)

**Comment by Exide** [comment]
I was unable to produce this with a simple test. I'll keep the issue open for a while to collect more info.

**Comment by Paul-Hess** [comment]
closed because better testing added by #1211 and stakeholders have not seen the issue reappear
