### ISSUE TITLE
Update js dependencies for integration tests

### ISSUE THREAD

**Issue by Paul-Hess** [flightstats/hub#1043]
npm runs it's own security checks on dependencies now.
We have some deprecations and vulnerabilities that should be updated or replaced:

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

npm WARN notice [SECURITY] qs has the following vulnerability: 2 high. Go here for more details: https://nodesecurity.io/advisories?search=qs&version=0.6.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.3.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=0.9.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.2.11 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] hawk has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hawk&version=1.0.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] ws has the following vulnerabilities: 2 high, 1 low. Go here for more details: https://nodesecurity.io/advisories?search=ws&version=0.4.32 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=request&version=2.33.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

**Comment by Paul-Hess** [comment]
This can be closed, I'll leave for someone else to push the button

**Comment by Exide** [comment]
Woo!
