### ISSUE TITLE
request to /previous returns a 303

### ISSUE THREAD

**Issue by Paul-Hess** [flightstats/hub#1073]
Steps to reproduce: 

  create channel
     ex: http://192.168.99.100/channel/TeSt_0_47580804908476404
  POST 3 items into the channel
  
  GET the latest item in the channel url
    ex: http://192.168.99.100/channel/TeSt_0_47580804908476404/2018/08/08/21/40/13/011/ApgRYu

GET the previous unstable item from the latest

curl http://192.168.99.100/channel/TeSt_0_47580804908476404/2018/08/08/21/40/13/011/ApgRYu/previous?stable=false

// returns ''

curl -L http://192.168.99.100/channel/TeSt_0_47580804908476404/2018/08/08/21/40/13/011/ApgRYu/previous?stable=false

// follows redirect and returns resource

To my understanding the original GET to /previous should return the resource (with a 200).
It looked like it was because our client module in the tests follows redirects silently.
Not sure this is a bug because a 303 is the semantic response here IMHO, but the docs may need an update to reflect the often hidden 303 response.

**Comment by Exide** [comment]
As we discussed, this is intended behavior that could be spelled out in the documentation better. I'm going to leave the documentation tag to remind me to update the docs.
