### ISSUE TITLE
Group Callback Spikes can overwhelm CPU

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#159]
When a group callback has many parallel processes, a spike in data can cause a large spike in CPU usage.  This can adversely impact other traffic to the hub.

Mitigation:
(non - coding solutions)
- Increase hub node size to accommodate the spikes - more AWS spend for normal traffic.
- Reduce the number of parallel callbacks manually  (conversations with callback owners)

(dev solutions)
Callback only Hub node - in addition to the traditional 3 - so callbacks won't affect other traffic
Spin up node as needed (might be SciFi)
Improve performance of hub processes

**Comment by moulliet** [comment]
upsized prod hub servers
