### ISSUE TITLE
Optional parameter to actually pass the data when setting up webhooks...

### ISSUE THREAD

**Issue by aashishpatel** [flightstats/hub#263]
... instead of having the client retrieve manually.

Is anyone not using group callbacks without fetching the data again(I know that the callback payload has a list of uri's - always 1)?

**Comment by moulliet** [comment]
Aashish would like this to work for the encrypted hub.  Therefore, we would need to have a group interface underneath the protected /channel API.

Also, we should either protect the tag interface via ACLs, or we should make it optional an remove it from the encrypted hub.

**Comment by Exide** [comment]
Probably wont implement due to complexity with large hub payloads. Which are increasingly common.
