### ISSUE TITLE
Allow hyphen in channel name

### ISSUE THREAD

**Issue by zradick** [flightstats/hub#292]
Now that Cassandra is out of the picture can we have hyphens in channel names?  I have tried numerous times to make channels with them and the results are surprising.

**Comment by moulliet** [comment]
Is the surprise that hyphens are not allowed, or something else?
I think you should get a 400 response every time.

**Comment by zradick** [comment]
Sorry, I was fooled by some code on our side that was trying to work around the no-hyphens issue by silently changing the name for me (leaving off everything after the hyphen -- cute).  So it was working but only because of something silly on my side of the equation.  400 seems like an appropriate response in the face of an unusable name.
