### ISSUE TITLE
Channel create with no data returns 400 on existing channel

### ISSUE THREAD

**Issue by chriskessel** [flightstats/hub#300]
I've got a chunk of code that always tries to create a channel and doesn't care if it already exists. If you do a PUT with no data, the subsequent attempts return a 400. The same request with data returns 201. It should probably be consistent in the return code.

If the channel already exists, this returns 201:
curl -i -X PUT http://hub-v2.svc.dev/channel/crktest --data '{"description":"foo"}' --header "Content-type: application/json"

But this returns 400:
curl -i -X PUT http://hub-v2.svc.dev/channel/crktest

**Comment by breedx2** [comment]
Does the second one actually create the channel?

**Comment by chriskessel** [comment]
No, because the channel already exists on the 2nd call...

Maybe I haven't explained this appropriately. Both PUTs create the channel initially. The PUTs behave differently on the 2nd attempt. My thought is it'd be nice if they both behaved the same (as far as return code) regardless of if the channel already existed.

As it is, I have a chunk of code "ensureChannelExists()" that passes in some json channel metadata purely so I always get back the same return code.

**Comment by breedx2** [comment]
If the intended semantic is to replace any current config with the defaults, then I think I agree that it should 201.

**Comment by chriskessel** [comment]
I think the semantics would be the same as sending in an empty json string "{}", which I think means to change nothing.
