### ISSUE TITLE
Could the retry interval for group callback be made configurable + expiration

### ISSUE THREAD

**Issue by aashishpatel** [flightstats/hub#303]
basically, we are creating custom channels for pushing data data for a customers endpoint, if we could set/change the interval at which failures are retried that would help us a ton.  Also it would be cool if we had an expiration for the retries.

for example: a customer would like us to deliver a message to them ever x minutes and stop trying if the data is more than y minutes old.

**Comment by aashishpatel** [comment]
@cmwood @rdarrelbonner @gnopai does this request sound good for what we're trying to to to deliver alerts to alaska/customers?  remember it's per route.

**Comment by moulliet** [comment]
Currently, the hub retries callbacks with an exponential delay, up to a capped limit of one minute.  
What delay would you like?

Giving up on old items sounds doable.

**Comment by aashishpatel** [comment]
Our use case is fairly simply, customers want alerts delivered to them in a timely manner, however they probably don't care about getting stale alerts. We currently have an admin console to allows pro-services to create delivery channel on the hub for a customer. Typically the customers will specify the delay interval on retries - say 15 minutes for up to 60 minutes.

both setting would be optional and on the group callback.  On failure to deliver it would retry every 15 minutes for up to 1 hour.

We are going to talk more about this today, so just let this bake for now.
