### ISSUE TITLE
Ensure certain high value data can not be deleted

### ISSUE THREAD

**Issue by stevenstark** [flightstats/hub#338]
Currently, anyone within the FlightStats network can issue a 'DELETE' request that will remove a Hub channel in production.  While this is very valuable and helpful in development and staging, it is risky in production.  My specific concern is with Processed Flight Histories.  We are working on a new API - Historical Flight Status - which will provide flight status for flights going back as far as we have data.  Initially, we are going to use Processed Flight Histories to populate our data set.  We want to make sure that we can always rely on going back to P.F.H to recreate our data set in case of any issues.  In other words, we are assuming PFH is the long-term, stable, canonical representation of our Flight Status data.  In order to do this we need to be sure it won't be deleted.

**Comment by moulliet** [comment]
this is resolved by #287
