### ISSUE TITLE
Certain text content cannot be posted to a channel

### ISSUE THREAD

**Issue by breedx2** [flightstats/hub#382]
This is very strange behavior indeed.  Some combinations of input data cannot be written to the hub.

```
$ curl -i -X POST -H 'Content-Type: text/plain' --data '() {' http://hub.svc.staging/channel/jjptest
curl: (56) Recv failure: Operation timed out
```

but if I remove the first character, it posts just fine:
```
$ curl -i -X POST -H 'Content-Type: text/plain' --data ') {' http://hub.svc.staging/channel/jjptest
HTTP/1.1 201 Created
<snip>
```

Furthermore, if you just remove the space between the parens and the curly brace, it also works:
```
$ curl -i -X POST -H 'Content-Type: text/plain' --data '(){' http://hub.svc.staging/channel/jjptest
HTTP/1.1 201 Created
<snip>
```

**Comment by moulliet** [comment]
I can reproduce the issue from a jasmine-node test.
However, the Hub's tracing filter, which is at the top of the callstack, records a 201 response, and an item is created.
The hub's proxy also records a 201 response.
I can not reproduce the error running against my localhost's hub.

**Comment by moulliet** [comment]
This is an issue in the network.
