### ISSUE TITLE
Spoke /latest can be incorrect

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#411]

**Comment by allumbra** [comment]
The issue that we are seeing is that for a latest query, spoke did not find an item from the spokeResource.latest, but the item was later found when the latest performs a general previous query.

https://s3.amazonaws.com/uploads.hipchat.com/121751/910328/Hv1Hv6QBseqmiWM/spoke-latest.txt

**Comment by allumbra** [comment]
Tests in FileSpokeStoreTest.testIssue411 so far have failed to reproduce the issue.
