### ISSUE TITLE
Bug:  No Latest (channel is empty) reported for non empty channel

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#473]
Channel is not empty.  Earliest has a value.  This is for a max_items channel

http://hub.svc.dev/channel/ref_countries_json/status

`{
"_links": {
"self": {
"href": "http://hub.svc.dev/channel/ref_countries_json/status"
},
"latest": {
"href": "http://hub.svc.dev/channel/ref_countries_json/latest",
"message": "channel is empty"
},
"earliest": {
"href": "http://hub.svc.dev/channel/ref_countries_json/2016/01/14/19/02/01/050/w9M4fK"
}
}
}`

**Comment by moulliet** [comment]
This may have been a holdover from some issues we had with caching the latest value.
Fixed by resetting value in the ZooKeeper cache.
