### ISSUE TITLE
Make sure DataDog information has correct channel and tag

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#627]
<img width="581" alt="screen shot 2016-10-04 at 5 48 38 pm" src="https://cloud.githubusercontent.com/assets/5685787/19097616/ecd890b4-8a5a-11e6-8065-20893bde85c2.png">
<img width="584" alt="screen shot 2016-10-04 at 5 47 38 pm" src="https://cloud.githubusercontent.com/assets/5685787/19097615/ecd70ee2-8a5a-11e6-94fe-8862bf930599.png">

**Comment by Exide** [comment]
I made a commit (d044ac843e1f695f0b6e8f02001872870c7aa0b9) to resolve the missing channel info on the ```POST /internal/s3batch/{channel}``` call.

I can't seem to reproduce the ```GET /tag/{tag}/{y}/{m}/{d}/{h}/{m]/{s}/{ms}/{hash}``` one. I'm leaving this open while I try to dig up more information.
