### ISSUE TITLE
Bug with /previous with BATCH channel in S3

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#649]
The /previous results of the BATCH channels did not align with the results from /next

**Comment by moulliet** [comment]
This is an example of the call:

"_links": {
"self": {
"href": "http://hub/channel/stumptown/2016/10/31/23/11/54/586/20c0ki000003/p/3?trace=true"
},
"next": {
"href": "http://hub/channel/stumptown/2016/10/31/23/11/54/586/20c0ki000002/next/3?trace=true"
},
"previous": {
"href": "http://hub/channel/stumptown/2016/10/31/22/59/57/825/zJrvIq000016/previous/3?trace=true"
},
"uris": [
"http://hub/channel/stumptown/2016/10/31/22/59/57/825/zJrvIq000016",
"http://hub/channel/stumptown/2016/10/31/23/11/54/586/20c0ki000001",
"http://hub/channel/stumptown/2016/10/31/23/11/54/586/20c0ki000002"
]
},


zJrvIq000016 should not be in the list, as there many items in the 11 minutes between it and 20c0ki000001.

If I change any path elements of the url (exclusive of the last 6 characters of the hash sequence), the correct results are returned.

**Comment by lucasmo** [comment]
I've also noticed that if you request /previous/10, the 1st URI returned will be incorrect (several minutes off), but the next 9 URIs returned will be correct.

**Comment by moulliet** [comment]
Yes, it appears the issue is limited to previous queries on Batch channels where the start item is one of a bulk uploaded series, and the data is outside the Spoke window.
