### ISSUE TITLE
Allow prevention of zero byte hub items

### ISSUE THREAD

**Issue by chriskessel** [flightstats/hub#656]
When creating a hub item, I never want a zero byte item. Unfortunately, it's easy to accidentally create them if the code doing the POST doesn't check the entity before posting.

It'd be nice if the hub supported a way to prevent zero byte items from being posted. Perhaps some metadata on the channel itself? I'd guess that enforcement of this would typically be desired for every item in a channel rather than on an item by item basis.

**Comment by moulliet** [comment]
I am curious if anyone is relying on zero byte behavior in their application.

**Comment by moulliet** [comment]
@chriskessel is there any value in preventing items smaller (or larger) than an specified value?

**Comment by chriskessel** [comment]
Dev services don't have any scenarios where we'd know a hard limit on min/max size (other than avoiding the original zero-byte case).
