### ISSUE TITLE
Feature Request: Allow only payloads to be downloaded as a bulk request

### ISSUE THREAD

**Issue by berkley** [flightstats/hub#659]
I'd like a bulk download that includes only payloads.  For instance, do download a day's worth of data, I recently used this command:

curl http://hub.iad.prod.flightstats.io/channel/flightradar24Raw/2016/11/01?bulk=true

If I set accepts: application/zip, I get a zip file with payloads loaded in a directory structure that matches the IDs of the payloads.  If I don't set accepts, I get MIME content with lots of metadata.  What I really want is just the payloads in a text (json, xml, etc) file.  

I'd expect to be able to do (something like) this query: 

curl http://hub.iad.prod.flightstats.io/channel/flightradar24Raw/2016/11/01?bulk=true&payloadsOnly=true

To just return the payloads for 2016/11/01

**Comment by crozierm** [comment]
@berkley Do you have a current use case for this?

**Comment by berkley** [comment]
No, I think this was from when I was building the positional tracker app.
