### ISSUE TITLE
Explore strategies for horizontal scaling

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#668]
All existing clustered hub deploys use three hub nodes.
As we scale our instance sizes larger, the marginal cost can increase sharply.

For example, increasing the available cpu by switching from m4.xlarge to c4.2xlarge increases the cluster cost by 75-90%.

This may involve breaking up the Hub/Spoke systems, as Spoke needs more memory for the OS file system cache. 
A Spoke sharding mechanism could allow each Spoke instance to hold a fraction of the total data in memory.

**Comment by benFlightStats** [comment]
The EFS proposal would obviate spoke - and should enable horizontal scaling.
