### ISSUE TITLE
Caching for Batched storage in S3

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#705]
After an item is expired from Spoke, a single item GET must go to S3.  If the channel is using BATCH storage, this pattern can cause resource issues within the hub for a moderate volume of requests.

**Comment by moulliet** [comment]
A possible solution:
For a BATCH channel, single item GET outside of Spoke TTL
Check the batch cache first
else read batch item from S3
write batch item to batch cache
return requested single item

Clear batch cache more frequently than Spoke TTL
10 minutes?  30 minutes?

**Comment by Exide** [comment]
This is done.
