### ISSUE TITLE
Replication Catchup

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#730]
If replication falls behind (due to target system being down), the backlog of items are replayed.
Since replication uses a webhook with Second batching, all seconds must be sent to the client.
This could be optimized by changing the batching to Minute, or by not sending empty seconds, or ?

**Comment by benFlightStats** [comment]
Plan: add a new parameter to the webhook meta-data.  Name TBD (for now "fastforwardable" = bool).

If this is set to true, then if a webhook gets behind by a certain amount, then it will transition from second to minute bulk payloads.  When it catches up, it will resume second payload.

**Comment by benFlightStats** [comment]
Fixed
