### ISSUE TITLE
Fix locust to use given log file

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#781]
in 
[hubTasks.py](https://github.com/flightstats/hub/blob/7c3463aa767e25f4dcb0b9a346be491f519faf23/src/test/load/hubTasks.py#L17)

is directly using a file name, rather than using a parameter passed in.
`fh = logging.FileHandler('./locust.log')`

[Locust](http://locust.io/) may make getting access to a parameter difficult.

**Comment by benFlightStats** [comment]
@snarfmonkey You recently fixed this, nicht wahr?

**Comment by moulliet** [comment]
this is fixed
