### ISSUE TITLE
Full text search in docs?

### ISSUE THREAD

**Issue by JustinFarris** [flightstats/hub#797]
Is there any way to do a full text search on the hub docs site? Looks like it only searches page/section titles.

**Comment by benFlightStats** [comment]
Unfortunately no.  I think it also searches "tags".

**Comment by JustinFarris** [comment]
What are the chances of a feature request for that being feasible? Before the new pretty doc site, I could just "cmd/ctrl+f" to do a full text search easily. I've been getting a lot of questions from other FG folks that I'd love to give a polite "RTFM" answer to, but that's often more trouble than just R'ing TFM for them. :)

**Comment by benFlightStats** [comment]
It looks like an organ transplant on the tech I'm using.  I'll see what it would take.

**Comment by JustinFarris** [comment]
If that's the case, and you're married to this tech, maybe a "click here for a single-page version of these docs" would satisfy us greedy searchers.
