### ISSUE TITLE
Make BATCH the default storage strategy for channels

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#820]
Since this is always a good idea for channels that write > 1 time per minute, does the added cost for lower volume channels make this a bad default?

**Comment by moulliet** [comment]
One potential issue is usage of a high volume BATCH storage channel with single item GETs.
This pattern forces the hub to load up the entire batched data for a minute to retrieve a single item. Over and over.

**Comment by benFlightStats** [comment]
To summarize: BATCH is a reasonable default storage strategy except in the case of high volume channels that have single item GETs.

One possible solution is to return an error or warning http code if a high volume channel is being accessed this way.  However, this would require the hub to know this is a high volume channel somehow (which is a separate problem altogether).

Possible solution #2: Do throttling at the load balancer.  However, the throttling for this scenario would be different, I imagine, than the non batched GET rate.  

Possible solution #3: cache s3 batches.  This is probably overkill for this problem.

**Comment by benFlightStats** [comment]
Marking this as wont fix for now.  We will address best practices with the users as issues come up for now.
