### ISSUE TITLE
Ability to reconfigure the webhook lastUpdated to replay or skip items

### ISSUE THREAD

**Issue by chriskessel** [flightstats/hub#843]
A hub solution Dev Services uses is we manually track the last URI we've processed in a DB and iterate forward, so if we need to skip forward or backwards, we just clobber that DB value with a new value. The drivers for skipping forward or backwards are things like:

* We had a DB issue and want to replay data from the hub (skip backwards)
* We have bad data we put into the hub and we need to skip past it
* We're using the hub as a FIFO queue for delivery to somewhere else and if we've gotten behind, we want to skip forward. This case is typically for time sensitive data so it's better to bypass a bunch of data than try to claw our way back to current.

Because of those cases, we won't use webhooks, but if we could reset the webhook starting item then we could get rid of our manual "last hub item processed" state tracking.

An alternative is deleting the old webhook and creating a new one to replace it, but that feels like it might be abusing delete/create for the use case at hand.

**Comment by moulliet** [comment]
Sounds reasonable.
Do you imagine this would work by the client doing a PUT to the webhook with a new startItem?

**Comment by chriskessel** [comment]
That seems reasonable, that'd give it a similar feel to overriding a previous setting on a channel.

**Comment by Exide** [comment]
Instead of changing ```startItem``` on an existing webhook, would it make more sense to change ```lastUpdated```?

The question is more about semantics than a functional difference.

**Comment by chriskessel** [comment]
That makes sense to me assuming lastUpdated is what's used to decide what the next callback would be.

**Comment by moulliet** [comment]
lastUpdated does sound like a more appropriate choice.

**Comment by benFlightStats** [comment]
what do you guys think about a parameter called "updateCursor".  This would be a transient value passed in the config json that would update the lastUpdated as requested above.  Semantically I like it better.

**Comment by chriskessel** [comment]
Setting updateCursor to actually change lastUpdated feels odd. It feels like I'm calling a setter, but then it's setting some other variable. If I want to change lastUpdated, I'd expect to call a setter on lastUpdated.

**Comment by benFlightStats** [comment]
https://flightstats.github.io/hub/hub_notifications_webhooks.html#update-a-webhook-cursor

Will be in the 8/17 release
