### ISSUE TITLE
Fix integration tests the single hub can't handle

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#867]
We have a number of jasmine-node tests which test whether hub.type === 'aws' from hub/internal/properties 
These should be implemented for the single hub, where possible.

**Comment by Exide** [comment]
Everywhere ```hub.type === 'aws'``` is used in our tests relates to large items.

- [insert_and_fetch_large_historical_spec.js#L32](https://github.com/flightstats/hub/blob/master/src/test/javascript/integration/insert_and_fetch_large_historical_spec.js#L32)
- [insert_and_fetch_large_spec.js#L30](https://github.com/flightstats/hub/blob/master/src/test/javascript/integration/insert_and_fetch_large_spec.js#L30)
- [item_length_large_spec.js#L29](https://github.com/flightstats/hub/blob/master/src/test/javascript/integration/item_length_large_spec.js#L29)
- [sorted_query_spec.js#L108](https://github.com/flightstats/hub/blob/master/src/test/javascript/integration/sorted_query_spec.js#L108)
- [webhook_localhost_spec.js#L50](https://github.com/flightstats/hub/blob/master/src/test/javascript/integration/webhook_localhost_spec.js#L50)

So we can either implement large item support in the single hub or close this issue.
