### ISSUE TITLE
Tags cannot be added to a replicated channel

### ISSUE THREAD

**Issue by crozierm** [flightstats/hub#890]
$ curl -v -H Content-Type:application/json -d '{"tags":["historicalProcessedFlightHistory-tag"]}' https://marketplace.flightstats.com/channel/ProcessedFlightHistory?apikey=secret
*   Trying 52.5.72.189...
* TCP_NODELAY set
* Connected to marketplace.flightstats.com (52.5.72.189) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.flightstats.com
* Server certificate: Gandi Standard SSL CA 2
* Server certificate: USERTrust RSA Certification Authority
> POST /channel/ProcessedFlightHistory?apikey=secret HTTP/1.1
> Host: marketplace.flightstats.com
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 49
>
* upload completely sent off: 49 out of 49 bytes
< HTTP/1.1 403 Forbidden
< Date: Mon, 14 Aug 2017 18:05:15 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: origin, content-type, accept, authorization
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
< Server: Hub/2017.08.09.310.master
< Vary: Accept-Encoding
< Access-Control-Expose-Headers: origin,content-type,accept,authorization
< X-Kong-Upstream-Latency: 4
< X-Kong-Proxy-Latency: 0
< Via: kong/0.10.3
<
* Connection #0 to host marketplace.flightstats.com left intact
ProcessedFlightHistory cannot modified while replicating

**Comment by moulliet** [comment]
The curl command should have -X PUT, which works as expected.
