### ISSUE TITLE
Allow tag webhooks

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#901]
In the same way that tags allow query operations on a group of channels, a tag webhook would create webhooks on a group of channels.
As the channel membership of the tag changes, the webhooks would be stopped and started.

This feature would simplify the maintenance of many webhooks all delivering to the same destination.  
Individual webhooks should be accessible for monitoring, pausing and cursor ops.

**Comment by Exide** [comment]
This was resolved with #950
