### ISSUE TITLE
Add a link on the Hub UI to show the docs for a channel (/channel/X/doc)

### ISSUE THREAD

**Issue by berkley** [flightstats/hub#942]
I'd like to be able to access the docs for a channel on the channel metadata page.  

![image](https://user-images.githubusercontent.com/162088/31359505-1cdfd0f2-acff-11e7-94af-55c4e3dc577d.png)

**Comment by Exide** [comment]
I'm moving this over to the hub-ui repo: https://github.com/flightstats/hub-ui/issues/2
