### ISSUE TITLE
Documentation about how to run your own copy

### ISSUE THREAD

**Issue by jkwatson** [flightstats/hub#96]
Mostly, would love some docs on how to set up the back end, etc.

Thanks!

**Comment by moulliet** [comment]
Yes, we should do that :)
This needs to be cleaned up - https://github.com/flightstats/hub/wiki/Set-up-a-new-environment

Also, have you run it locally?
https://github.com/flightstats/hub/wiki/Install-the-Hub-locally

**Comment by jkwatson** [comment]
Haven't tried yet, but it's on the todo list.

**Comment by moulliet** [comment]
Here's some better documentation:
https://github.com/flightstats/hub/wiki/Hub-Technical-Details
https://github.com/flightstats/hub/wiki/Install-a-Hub-Cluster

Please let us know if you have any questions and issues.
Also, we could probably put together a pairing session to get you setup.
