### ISSUE TITLE
Creating a Channel without a body gives 500 NPE

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#98]
Create a channel with Body works as expected but:

curl -i -X PUT http://hub/channel/testBen2 

returns

HTTP/1.1 500 Server Error
Date: Tue, 24 Feb 2015 20:28:35 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html; charset=ISO-8859-1
Content-Length: 315
Server: Jetty(9.2.6.v20141205)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /channel/testBen2. Reason:
<pre>    java.lang.NullPointerException</pre></p>

**Comment by moulliet** [comment]
fixed with https://github.com/flightstats/hub/pull/102
