### ISSUE TITLE
Feature Request: give up on callback after X tries/Y time passed

### ISSUE THREAD

**Issue by chriskessel** [flightstats/hub#986]
Dev Services, for reworking the eventing queue management, would like a callback configure where the hub would give up on a callback if it fails more than X times. A similar variant, give up if a callback is older than Y amount of time.

The concrete uses cases are:
* If a customer fails to successfully handle an event posted to their endpoint 5 times, we throw away that event
* If an event is more than 15 minutes delays, the customer doesn't want it anymore, we can throw it away.

**Comment by moulliet** [comment]
Failing after X attempts is a new feature.

Webhooks currently support ttlMinutes : "ttlMinutes is optional and defaults to 0. If ttlMinutes is greater than 0, the hub will not attempt to send an item which is older than the ttl."
https://flightstats.github.io/hub/hub_notifications_webhooks.html
